services:
  app:
    build:
      context: .
      args:
        STINGRAYTOOLS_REF: dev
        STINGRAYTOOLS_REPO: https://github.com/anhph95/stingraytools.git
    container_name: stingray-dashboard

    ports:
      - "8050:8050"

    volumes:
      - ./dash_data:/dash_data:ro

    environment:
      PYTHONUNBUFFERED: "1"

    restart: unless-stopped
