services:
  dash:
    build:
      context: .
    container_name: stingray-dashboard

    ports:
      - "8050:8050"

    volumes:
      - ./dash_data:/dash_data

    environment:
      DASH_DEBUG: "1"
      PYTHONUNBUFFERED: "1"

    command: >
      gunicorn
      --bind 0.0.0.0:8050
      stingray_dashboard.app:application

    restart: unless-stopped
